INSERT INTO products (sku, product_title, description, quantity, price) VALUES
                                                                            ('SKU001', 'Notebook Gamer', 'Notebook de alto desempenho para jogos', 10, 5999.90),
                                                                            ('SKU002', 'Smartphone Android', 'Celular com sistema Android', 25, 1999.99),
                                                                            ('SKU003', 'Smart TV 55 polegadas', 'Televisão inteligente 4K', 8, 3499.00),
                                                                            ('SKU004', 'Fone de Ouvido Bluetooth', 'Fone sem fio com cancelamento de ruído', 50, 299.90),
                                                                            ('SKU005', 'Teclado Mecânico', 'Teclado gamer com iluminação RGB', 30, 399.00),
                                                                            ('SKU006', 'Mouse Óptico', 'Mouse USB de alta precisão', 40, 89.90),
                                                                            ('SKU007', 'Monitor 24 polegadas', 'Monitor LED Full HD', 15, 899.00),
                                                                            ('SKU008', 'Impressora Multifuncional', 'Impressora, scanner e copiadora', 12, 699.00),
                                                                            ('SKU009', 'Câmera Digital', 'Câmera compacta 20MP', 7, 1299.00),
                                                                            ('SKU010', 'Tablet 10 polegadas', 'Tablet Android com 64GB', 20, 1199.00),
                                                                            ('SKU011', 'Caixa de Som Portátil', 'Bluetooth, bateria de longa duração', 35, 249.90),
                                                                            ('SKU012', 'HD Externo 1TB', 'Armazenamento portátil USB 3.0', 18, 399.00),
                                                                            ('SKU013', 'SSD 512GB', 'Unidade de estado sólido rápida', 22, 499.00),
                                                                            ('SKU014', 'Placa de Vídeo RTX', 'Placa gráfica para jogos', 5, 3499.00),
                                                                            ('SKU015', 'Processador Intel i7', 'CPU de 10ª geração', 9, 1899.00),
                                                                            ('SKU016', 'Memória RAM 16GB', 'DDR4 para desktop', 16, 399.00),
                                                                            ('SKU017', 'Fonte ATX 600W', 'Fonte de alimentação para PC', 14, 299.00),
                                                                            ('SKU018', 'Gabinete Gamer', 'Gabinete com LED e vidro temperado', 11, 499.00),
                                                                            ('SKU019', 'Roteador Wi-Fi 6', 'Roteador de alta velocidade', 13, 599.00),
                                                                            ('SKU020', 'Switch de Rede 8 portas', 'Switch gigabit', 10, 249.00),
                                                                            ('SKU021', 'Microfone Condensador', 'Microfone para gravação', 17, 349.00),
                                                                            ('SKU022', 'Webcam Full HD', 'Câmera para videoconferência', 19, 199.00),
                                                                            ('SKU023', 'Carregador Portátil', 'Power bank 10.000mAh', 28, 129.90),
                                                                            ('SKU024', 'Relógio Smartwatch', 'Relógio inteligente com monitor cardíaco', 21, 499.00),
                                                                            ('SKU025', 'Pulseira Fitness', 'Monitor de atividades físicas', 24, 149.90),
                                                                            ('SKU026', 'Drone com Câmera', 'Drone com filmagem em HD', 6, 1599.00),
                                                                            ('SKU027', 'Console de Videogame', 'Console de última geração', 4, 3999.00),
                                                                            ('SKU028', 'Controle sem fio', 'Controle para videogame', 27, 299.00),
                                                                            ('SKU029', 'Headset Gamer', 'Fone com microfone para jogos', 23, 349.00),
                                                                            ('SKU030', 'Cadeira Gamer', 'Cadeira ergonômica para jogos', 8, 1299.00),
                                                                            ('SKU031', 'Mesa Digitalizadora', 'Mesa para desenho digital', 7, 699.00),
                                                                            ('SKU032', 'Leitor de Cartão SD', 'Leitor USB para cartões', 32, 49.90),
                                                                            ('SKU033', 'Pen Drive 64GB', 'Armazenamento portátil', 45, 69.90),
                                                                            ('SKU034', 'Adaptador USB-C', 'Adaptador para dispositivos USB-C', 38, 39.90),
                                                                            ('SKU035', 'Hub USB 3.0', 'Expansor de portas USB', 29, 89.90),
                                                                            ('SKU036', 'Projetor Portátil', 'Projetor para apresentações', 5, 1299.00),
                                                                            ('SKU037', 'Ventilador USB', 'Ventilador pequeno para mesa', 33, 59.90),
                                                                            ('SKU038', 'Luminária LED', 'Luminária de mesa com LED', 36, 79.90),
                                                                            ('SKU039', 'Estabilizador de Energia', 'Proteção para equipamentos eletrônicos', 9, 199.00),
                                                                            ('SKU040', 'Nobreak 1200VA', 'Fonte de energia ininterrupta', 3, 899.00),
                                                                            ('SKU041', 'Scanner de Documentos', 'Scanner portátil', 6, 499.00),
                                                                            ('SKU042', 'Gravador de Voz Digital', 'Gravador portátil', 14, 199.00),
                                                                            ('SKU043', 'Rádio Bluetooth', 'Rádio portátil com Bluetooth', 20, 129.90),
                                                                            ('SKU044', 'Caixa Registradora Eletrônica', 'Para estabelecimentos comerciais', 2, 1499.00),
                                                                            ('SKU045', 'Máquina de Cartão', 'Leitor de cartões para vendas', 13, 299.00),
                                                                            ('SKU046', 'Impressora 3D', 'Impressora para prototipagem', 1, 3999.00),
                                                                            ('SKU047', 'Placa-mãe ATX', 'Placa-mãe para desktop', 8, 799.00),
                                                                            ('SKU048', 'Cooler para Notebook', 'Base refrigerada para notebook', 17, 99.90),
                                                                            ('SKU049', 'Suporte para Monitor', 'Ajuste de altura para monitores', 22, 119.90),
                                                                            ('SKU050', 'Antena Wi-Fi', 'Antena para melhorar sinal', 26, 59.90);